development:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-dev'
test:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-test'
production:
   GEOIP_APP_KEY: 'PASTE APP ID HERE'
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
   S3_BUCKET: 'projectmeal-production'