development:
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
test:
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'
production:
   AWS_ACCESS_KEY_ID: 'PASTE ACCESS KEY ID HERE'
   AWS_SECRET_ACCESS_KEY: 'PASTE SECRET ACCESS KEY HERE'